---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flask-app
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./autodeploy2cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flask-app
  targetNamespace: app
