---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flask-app
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/khangalll/autodeploy2cluster
